vim.g.mapleader = " "
vim.g.maplocalleader = " "

vim.opt.cmdheight = 2
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.number = true
vim.opt.title = true
vim.opt.termguicolors = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.wrap = false
vim.opt.mouse = 'a' 
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.scrolloff = 10 
vim.opt.undofile = true 
vim.opt.backup = false 
vim.opt.signcolumn = 'yes:2'
vim.opt.updatetime = 250 
vim.opt.redrawtime = 10000 
vim.opt.inccommand = 'split'
